[package]
name = "run_and_prove"
version = "0.1.0"
edition = "2024"

[dependencies]
cairo-vm.workspace = true
clap.workspace = true
thiserror.workspace = true
cairo-program-runner-lib.workspace = true
stwo-cairo-adapter.workspace = true
