[workspace]
members = [
    "crates/cairo-program-runner",
    "crates/cairo-program-runner-lib",
    "crates/stwo_run_and_prove",
    "crates/vm_runner",
]
resolver = "2"

[workspace.dependencies]
bincode = { version = "2.0.1", features = [
    "serde",
] }
cairo-lang-executable = { git = "https://github.com/starkware-libs/cairo.git", rev = "86eb25173f9d8700adbd2770406d715fbf1bb9f8" }
cairo-lang-runner = { git = "https://github.com/starkware-libs/cairo.git", rev = "86eb25173f9d8700adbd2770406d715fbf1bb9f8" }
cairo-lang-casm = { git = "https://github.com/starkware-libs/cairo.git", rev = "86eb25173f9d8700adbd2770406d715fbf1bb9f8" }
cairo-lang-execute-utils = { git = "https://github.com/starkware-libs/cairo.git", rev = "86eb25173f9d8700adbd2770406d715fbf1bb9f8" }
cairo-program-runner-lib = { path = "crates/cairo-program-runner-lib" }
cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", rev = "e2c6c91c73cd0bc351721f302390fcc0965c6224", features = [
    "extensive_hints",
    "mod_builtin",
    "clap",
] }
clap = { version = "4.3.10", features = ["derive"] }
log = "0.4.21"
num-bigint = "0.4"
num-traits = "0.2.19"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
starknet-crypto = "0.7.4"
starknet-types-core = "0.1.2"
stwo_cairo_utils = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "8663128d3067c795afc3cba29a4f8399d4126f64" }
stwo-cairo-adapter = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "8663128d3067c795afc3cba29a4f8399d4126f64" }
stwo_cairo_prover = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "8663128d3067c795afc3cba29a4f8399d4126f64" }
stwo-cairo-serialize = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "8663128d3067c795afc3cba29a4f8399d4126f64" }
cairo-air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "8663128d3067c795afc3cba29a4f8399d4126f64" }
tempfile = "3.10.1"
thiserror = "1.0.61"
thiserror-no-std = "2.0.2"
tracing = "0.1.40"
sonic-rs = "0.3.17"
starknet-ff = "0.3.7"
mockall = "0.13.1"
rstest = "0.21"
