[workspace]
members = [
    "crates/cairo-program-runner",
    "crates/cairo-program-runner-lib",
    "crates/vm_runner",
]
resolver = "2"

[workspace.dependencies]
bincode = { version = "2.0.0-rc.3", default-features = false, features = [
    "serde",
] }
cairo-lang-executable = { git = "https://github.com/starkware-libs/cairo.git", rev = "e4521e8c8646fe4c61c51ef1253fae44044f5f38" }
cairo-lang-runner = { git = "https://github.com/starkware-libs/cairo.git", rev = "e4521e8c8646fe4c61c51ef1253fae44044f5f38" }
cairo-lang-casm = { git = "https://github.com/starkware-libs/cairo.git", rev = "e4521e8c8646fe4c61c51ef1253fae44044f5f38" }
cairo-lang-execute-utils = { git = "https://github.com/starkware-libs/cairo.git", rev = "e4521e8c8646fe4c61c51ef1253fae44044f5f38" }
cairo-program-runner-lib = { path = "crates/cairo-program-runner-lib" }
cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", rev = "9c44e1cef56c6ea557d6441e27ad3c756bbbe8a9", features = [
    "extensive_hints",
    "mod_builtin",
    "clap",
] }
clap = { version = "4.3.10", features = ["derive"] }
log = "0.4.21"
num-bigint = "0.4"
num-traits = "0.2.19"
regex = "1.11.1"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
starknet-crypto = "0.6.2"
starknet-types-core = "0.1.2"
stwo_cairo_utils = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "411853b189dcb4b149cec51d137bd0a8ca0dd0b3" }
stwo-cairo-adapter = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "411853b189dcb4b149cec51d137bd0a8ca0dd0b3" }
tempfile = "3.10.1"
thiserror = "1.0.61"
thiserror-no-std = "2.0.2"
tracing = "0.1.40"
