[package]
name = "cairo-bootloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-rc.3", default-features = false, features = ["serde"] }
cairo-vm = { git = "https://github.com/Alon-Ti/cairo-vm", rev = "f6b9e651f1c2cc4b3a5b94119cc81ad5036f8889", features = ["extensive_hints", "mod_builtin", "clap"] }
clap = { version = "4.3.10", features = ["derive"] }
num-traits = "0.2.19"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
starknet-crypto = "0.6.2"
starknet-types-core = "0.1.2"
tempfile = "3.10.1"
thiserror = "1.0.61"
thiserror-no-std = "2.0.2"

[dev-dependencies]
assert_matches = "1.5.0"
rstest = "0.19.0"

[[bin]]
name = "run_simple_bootloader"
