[package]
name = "cairo-program-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-rc.3", default-features = false, features = [
    "serde",
] }
cairo-vm = { version = "2.0.1", features = [
    "extensive_hints",
    "mod_builtin",
    "clap",
] }
cairo-lang-executable = { git = "https://github.com/starkware-libs/cairo.git", rev = "ddaec76b4364ca6e0af4d185a99904d13b93f81e" }
cairo-lang-runner = { git = "https://github.com/starkware-libs/cairo.git", rev = "ddaec76b4364ca6e0af4d185a99904d13b93f81e" }
cairo-lang-casm = { git = "https://github.com/starkware-libs/cairo.git", rev = "ddaec76b4364ca6e0af4d185a99904d13b93f81e" }
cairo-lang-execute-utils = { git = "https://github.com/starkware-libs/cairo.git", rev = "ddaec76b4364ca6e0af4d185a99904d13b93f81e" }
clap = { version = "4.3.10", features = ["derive"] }
num-traits = "0.2.19"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
starknet-crypto = "0.6.2"
starknet-types-core = "0.1.2"
tempfile = "3.10.1"
thiserror = "1.0.61"
thiserror-no-std = "2.0.2"
regex = "1.11.1"
num-bigint = "0.4"

[dev-dependencies]
assert_matches = "1.5.0"
rstest = "0.19.0"

[[bin]]
name = "cairo_program_runner"
