name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup show
      - run: rustup toolchain install nightly-2025-07-14 --profile minimal
      - run: rustup component add rustfmt --toolchain nightly-2025-07-14
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly-2025-07-14 fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup show
      - run: rustup toolchain install nightly-2025-07-14 --profile minimal
      - run: rustup component add clippy --toolchain nightly-2025-07-14
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly-2025-07-14 clippy --all -- -D warnings

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - run: rustup show
      - run: rustup toolchain install nightly-2025-07-14 --profile minimal
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: "Unit tests"
        run: |
          RUSTFLAGS="-D warnings" cargo +nightly-2025-07-14 test
      - name: "Test examples"
        run: |
          RUSTFLAGS="-D warnings" cargo +nightly-2025-07-14 run --example run_program

  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup show
      - run: rustup toolchain install nightly-2025-07-14 --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: cargo install cargo-udeps --locked
      - run: cargo +nightly-2025-07-14 udeps
