name: Upload-Artifacts

on:
  push:
    branches:
      - guy/main/test_artifacts_upload

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled
      - edited
    paths:
      - '.github/workflows/upload_artifacts_workflow.yml'

jobs:
  artifacts-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Get commit hash prefix for PR update
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "SHORT_HASH=${COMMIT_SHA:0:7}" >> $GITHUB_ENV

      - env:
          SHORT_HASH: ${{ github.event.pull_request.head.sha }}
        run: echo ${COMMIT_SHA}

      - run: cargo build -r

      - name: Authenticate with GCS
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.SA_GPS_ARTIFACTS_BUCKET_WRITER_ACCESS_KEY }}

      - name: Upload binary to GCP
        id: upload_file
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "target/release/cairo_program_runner"
          destination: "gps_artifacts/release/cairo_program_runner/${{ env.SHORT_HASH }}"
