name: Upload-Artifacts

on:
  push:
    branches:
      - noamp/align_adapter_and_sharp_format

jobs:
  artifacts-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Get commit hash prefix for PR update
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          echo "SHORT_HASH=${COMMIT_SHA:0:7}" >> $GITHUB_ENV

      - name: Install cross
        run: cargo install cross

      - name: Build all binaries (generic and znver5)
        run: |
          cargo build --release
          RUSTFLAGS="-C target-cpu=znver5 -C opt-level=3 -C codegen-units=1" cross build --release

      - name: Authenticate with GCS
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.SA_GPS_ARTIFACTS_BUCKET_WRITER_ACCESS_KEY }}

      - name: Upload cairo_program_runner x86_64 binary to GCP
        id: upload_cairo_program_runner_x86
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "target/release/cairo_program_runner"
          destination: "cairo_program_runner_artifacts/${{ env.SHORT_HASH }}/release"

      - name: Upload stwo_vm_runner x86_64 binary to GCP
        id: upload_stwo_vm_runner_x86
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "target/release/stwo_vm_runner"
          destination: "stwo_vm_runner_artifacts/${{ env.SHORT_HASH }}/release"

      - name: Upload stwo_run_and_prove binary to GCP
        id: upload_stwo_run_and_prove
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "target/release/stwo_run_and_prove"
          destination: "stwo_run_and_prove_artifacts/${{ env.SHORT_HASH }}/release"

      - name: Upload stwo_run_and_prove_znver5 binary to GCP
        id: upload_stwo_run_and_prove_znver5
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "target/x86_64-unknown-linux-gnu/release/stwo_run_and_prove"
          destination: "stwo_run_and_prove_znver5_artifacts/${{ env.SHORT_HASH }}/release"
